version: '3'
services:
  web-server:
    image: meetingflow-webapp
    restart: always
    depends_on:
      - mongo
    env_file:
      - production.env
    build:
      context: .
      dockerfile: .Dockerfile
    ports:
      - '8080:8080'
    volumes:
      - ./:/usr/src/app
    links:
      - mongo:mongo
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    volumes:
      - ./data:/data/db
