version: '3'
services:
  web-server:
    image: meetingflow-webapp
    build: 
      app:
    build:
      context: .
      dockerfile: .Dockerfile
    ports:
      - '8000:8000'
    volumes:
      - ./:/usr/src/app
